---
- name: Prepare variables
  set_fact:
    jenkins_job: "{{ jenkins_job | upper }}"
    jenkins_host: "http://localhost:{{ jenkins_port }}/{{ jenkins_prefix }}"

- include: install.yml
  when: "{{ jenkins_install }}"

- include: jobs.yml
