---
- name: Check if swap already enabled
  file:
    path: "{{ swap.file }}"
    state: touch
  register: is_swapfile

- name: Create swapfile if not present
  shell: "dd if=/dev/zero of={{ swap.file }} bs={{ swap.size }} count={{ swap.blocks }}"
  when: "{{ is_swapfile.changed and is_swapfile.size == 0 }}"

- name: Make swapfile as swap
  shell: "mkswap {{ swap.file }}"

- name: Check if swap enabled as swapon
  shell: "swapon -s"
  register: swapon

- name: Enable swap
  shell: "swapon {{ swap.file }}"
  when: "{{ swapon.stdout.find(swap.file) == -1 }}"

- name: Add swap to fstab
  mount:
    src: "{{ swap.file }}"
    opts: default
    name: swap
    state: present
    fstype: swap
