---
- name: Prepare MySQL temporary directory
  file:
    path: "{{ mysql_tmpdir }}"
    state: "{{ item }}"
  with_items:
    - absent
    - directory

- name: Prepare SHM directory
  file:
    path: /run/shm/mysql
    mode: 0777
    group: mysql
    owner: mysql
    recurse: yes

- name: Adding tmpdir preparation to rc.local
  lineinfile: dest=/etc/rc.local regexp="^exit 0" insertbefore=yes line="rm -rf /run/shm/mysql && mkdir /run/shm/mysql || true && chown mysql:mysql /run/shm/mysql && chmod -R 777 /run/shm/mysql"

- name: Disable apparmor
  shell: update-rc.d -f apparmor remove
  notify: restart mysql
  ignore_errors: yes

- name: Apparmor
  shell: "/etc/init.d/apparmor {{ item }}"
  ignore_errors: yes
  with_items:
    - teardown
    - stop

- name: Setting mysqld to complain mode
  shell: aa-complain /usr/sbin/mysqld
  ignore_errors: yes

- name: Add preconfigured settings to my.cnf file
  ini_file:
    dest: /etc/mysql/my.cnf
    value: "{{ item.value }}"
    option: "{{ item.option }}"
    section: "{{ item.section }}"
  with_items: "{{ my_cnf }}"
  notify: restart mysql
